type IconDef = {
  glyph: string
  color?: string
}

const ICON_MAP: Record<string, IconDef> = {
  '.ts': { glyph: 'type-submodule', color: '#519aba' },
  '.tsx': { glyph: 'type-submodule', color: '#519aba' },
  '.mts': { glyph: 'type-submodule', color: '#519aba' },
  '.cts': { glyph: 'type-submodule', color: '#519aba' },
  '.js': { glyph: 'type-script', color: '#cbcb41' },
  '.jsx': { glyph: 'type-script', color: '#cbcb41' },
  '.mjs': { glyph: 'type-script', color: '#cbcb41' },
  '.cjs': { glyph: 'type-script', color: '#cbcb41' },
  '.json': { glyph: 'json', color: '#cbcb41' },
  '.jsonc': { glyph: 'json', color: '#cbcb41' },
  '.jsonl': { glyph: 'json', color: '#cbcb41' },
  '.css': { glyph: 'symbol-color', color: '#56b6c2' },
  '.scss': { glyph: 'symbol-color', color: '#c6538c' },
  '.sass': { glyph: 'symbol-color', color: '#c6538c' },
  '.less': { glyph: 'symbol-color', color: '#56b6c2' },
  '.styl': { glyph: 'symbol-color', color: '#c552a0' },
  '.postcssrc': { glyph: 'symbol-color', color: '#dd3a0c' },
  '.html': { glyph: 'html', color: '#e34c26' },
  '.htm': { glyph: 'html', color: '#e34c26' },
  '.xhtml': { glyph: 'html', color: '#e34c26' },
  '.xml': { glyph: 'code', color: '#a074c4' },
  '.svg': { glyph: 'symbol-color', color: '#ffb13b' },
  '.xsl': { glyph: 'code', color: '#a074c4' },
  '.png': { glyph: 'file-media', color: '#a074c4' },
  '.jpg': { glyph: 'file-media', color: '#a074c4' },
  '.jpeg': { glyph: 'file-media', color: '#a074c4' },
  '.gif': { glyph: 'file-media', color: '#a074c4' },
  '.webp': { glyph: 'file-media', color: '#a074c4' },
  '.ico': { glyph: 'file-media', color: '#a074c4' },
  '.bmp': { glyph: 'file-media', color: '#a074c4' },
  '.avif': { glyph: 'file-media', color: '#a074c4' },
  '.md': { glyph: 'markdown', color: '#519aba' },
  '.mdx': { glyph: 'markdown', color: '#519aba' },
  '.markdown': { glyph: 'markdown', color: '#519aba' },
  '.txt': { glyph: 'file-text', color: '#c5c5c5' },
  '.rtf': { glyph: 'file-text', color: '#c5c5c5' },
  '.yml': { glyph: 'tag', color: '#cbcb41' },
  '.yaml': { glyph: 'tag', color: '#cbcb41' },
  '.toml': { glyph: 'gear', color: '#858585' },
  '.env': { glyph: 'lock', color: '#e6d460' },
  '.env.local': { glyph: 'lock', color: '#e6d460' },
  '.env.example': { glyph: 'lock', color: '#e6d460' },
  '.sh': { glyph: 'terminal', color: '#858585' },
  '.bash': { glyph: 'terminal', color: '#858585' },
  '.zsh': { glyph: 'terminal', color: '#858585' },
  '.bat': { glyph: 'terminal', color: '#c5c5c5' },
  '.cmd': { glyph: 'terminal', color: '#c5c5c5' },
  '.ps1': { glyph: 'terminal', color: '#519aba' },
  '.py': { glyph: 'symbol-misc', color: '#519aba' },
  '.pyw': { glyph: 'symbol-misc', color: '#519aba' },
  '.pyi': { glyph: 'symbol-misc', color: '#519aba' },
  '.go': { glyph: 'code', color: '#519aba' },
  '.rs': { glyph: 'debug-breakpoint-log', color: '#dea584' },
  '.java': { glyph: 'coffee', color: '#cc3e44' },
  '.kt': { glyph: 'debug-breakpoint-log', color: '#7852c9' },
  '.kts': { glyph: 'debug-breakpoint-log', color: '#7852c9' },
  '.scala': { glyph: 'gear', color: '#cc3e44' },
  '.c': { glyph: 'symbol-misc', color: '#519aba' },
  '.cpp': { glyph: 'symbol-misc', color: '#519aba' },
  '.cc': { glyph: 'symbol-misc', color: '#519aba' },
  '.cxx': { glyph: 'symbol-misc', color: '#519aba' },
  '.h': { glyph: 'symbol-misc', color: '#a074c4' },
  '.hpp': { glyph: 'symbol-misc', color: '#a074c4' },
  '.cs': { glyph: 'type-submodule', color: '#519aba' },
  '.fs': { glyph: 'color-mode', color: '#519aba' },
  '.fsx': { glyph: 'color-mode', color: '#519aba' },
  '.rb': { glyph: 'symbol-misc', color: '#cc3e44' },
  '.erb': { glyph: 'symbol-misc', color: '#cc3e44' },
  '.gemspec': { glyph: 'symbol-misc', color: '#cc3e44' },
  '.php': { glyph: 'code', color: '#a074c4' },
  '.phtml': { glyph: 'code', color: '#a074c4' },
  '.swift': { glyph: 'debug-breakpoint-log', color: '#f05138' },
  '.dart': { glyph: 'type-submodule', color: '#519aba' },
  '.lua': { glyph: 'code', color: '#519aba' },
  '.pl': { glyph: 'code', color: '#519aba' },
  '.sql': { glyph: 'database', color: '#519aba' },
  '.graphql': { glyph: 'code', color: '#e535ab' },
  '.gql': { glyph: 'code', color: '#e535ab' },
  '.proto': { glyph: 'code', color: '#858585' },
  '.thrift': { glyph: 'code', color: '#858585' },
  '.diff': { glyph: 'diff-added', color: '#519aba' },
  '.patch': { glyph: 'diff-added', color: '#519aba' },
  '.lock': { glyph: 'lock', color: '#858585' },
  '.ttf': { glyph: 'symbol-ruler', color: '#a074c4' },
  '.otf': { glyph: 'symbol-ruler', color: '#a074c4' },
  '.woff': { glyph: 'symbol-ruler', color: '#a074c4' },
  '.woff2': { glyph: 'symbol-ruler', color: '#a074c4' },
  '.eot': { glyph: 'symbol-ruler', color: '#a074c4' },
  '.mp4': { glyph: 'file-media', color: '#a074c4' },
  '.webm': { glyph: 'file-media', color: '#a074c4' },
  '.mov': { glyph: 'file-media', color: '#a074c4' },
  '.avi': { glyph: 'file-media', color: '#a074c4' },
  '.mp3': { glyph: 'file-media', color: '#a074c4' },
  '.wav': { glyph: 'file-media', color: '#a074c4' },
  '.ogg': { glyph: 'file-media', color: '#a074c4' },
  '.flac': { glyph: 'file-media', color: '#a074c4' },
  '.zip': { glyph: 'file-zip', color: '#cbcb41' },
  '.tar': { glyph: 'file-zip', color: '#cbcb41' },
  '.gz': { glyph: 'file-zip', color: '#cbcb41' },
  '.7z': { glyph: 'file-zip', color: '#cbcb41' },
  '.rar': { glyph: 'file-zip', color: '#cbcb41' },
  '.bz2': { glyph: 'file-zip', color: '#cbcb41' },
  '.xz': { glyph: 'file-zip', color: '#cbcb41' },
  '.wasm': { glyph: 'gear', color: '#519aba' },
  '.dll': { glyph: 'gear', color: '#858585' },
  '.so': { glyph: 'gear', color: '#858585' },
  '.dylib': { glyph: 'gear', color: '#858585' },
  '.exe': { glyph: 'run', color: '#858585' },
  '.pdf': { glyph: 'file-pdf', color: '#c9404e' },
  '.csv': { glyph: 'table', color: '#519aba' },
  '.xlsx': { glyph: 'table', color: '#519aba' },
  '.xls': { glyph: 'table', color: '#519aba' },
  '.docx': { glyph: 'file-text', color: '#519aba' },
  '.pptx': { glyph: 'presentation', color: '#c9404e' },
  '.blend': { glyph: 'file-media', color: '#ea7600' },
  '.fbx': { glyph: 'file-media', color: '#a074c4' },
  '.obj': { glyph: 'file-media', color: '#a074c4' },
  '.gltf': { glyph: 'file-media', color: '#a074c4' },
}

const NAME_MAP: Record<string, IconDef> = {
  'package.json': { glyph: 'json', color: '#cbcb41' },
  'package-lock.json': { glyph: 'json', color: '#cbcb41' },
  'tsconfig.json': { glyph: 'json', color: '#519aba' },
  'tsconfig.build.json': { glyph: 'json', color: '#519aba' },
  'tsconfig.node.json': { glyph: 'json', color: '#519aba' },
  'jsconfig.json': { glyph: 'json', color: '#519aba' },
  '.eslintrc': { glyph: 'gear', color: '#519aba' },
  '.eslintrc.json': { glyph: 'gear', color: '#519aba' },
  '.eslintrc.js': { glyph: 'gear', color: '#519aba' },
  '.eslintrc.cjs': { glyph: 'gear', color: '#519aba' },
  '.prettierrc': { glyph: 'gear', color: '#519aba' },
  '.prettierrc.json': { glyph: 'gear', color: '#519aba' },
  '.prettierrc.js': { glyph: 'gear', color: '#519aba' },
  'babel.config.js': { glyph: 'gear', color: '#cbcb41' },
  '.babelrc': { glyph: 'gear', color: '#cbcb41' },
  'vite.config.ts': { glyph: 'gear', color: '#519aba' },
  'vite.config.js': { glyph: 'gear', color: '#519aba' },
  'tailwind.config.js': { glyph: 'gear', color: '#519aba' },
  'tailwind.config.ts': { glyph: 'gear', color: '#519aba' },
  'webpack.config.js': { glyph: 'gear', color: '#519aba' },
  'postcss.config.js': { glyph: 'gear', color: '#dd3a0c' },
  '.gitignore': { glyph: 'chrome-close', color: '#e8833a' },
  '.gitkeep': { glyph: 'repo', color: '#e8833a' },
  '.gitattributes': { glyph: 'repo', color: '#e8833a' },
  '.gitmodules': { glyph: 'repo', color: '#e8833a' },
  '.env': { glyph: 'lock', color: '#e6d460' },
  '.env.local': { glyph: 'lock', color: '#e6d460' },
  '.env.example': { glyph: 'lock', color: '#e6d460' },
  '.env.development': { glyph: 'lock', color: '#e6d460' },
  '.env.production': { glyph: 'lock', color: '#e6d460' },
  '.editorconfig': { glyph: 'gear', color: '#858585' },
  '.npmrc': { glyph: 'tag', color: '#cc3e44' },
  '.npmignore': { glyph: 'tag', color: '#cc3e44' },
  '.nvmrc': { glyph: 'symbol-misc', color: '#519aba' },
  '.dockerignore': { glyph: 'vm', color: '#519aba' },
  '.vscodeignore': { glyph: 'extensions', color: '#519aba' },
  readme: { glyph: 'markdown', color: '#519aba' },
  'readme.md': { glyph: 'markdown', color: '#519aba' },
  'readme.txt': { glyph: 'file-text', color: '#c5c5c5' },
  changelog: { glyph: 'book', color: '#c5c5c5' },
  'changelog.md': { glyph: 'book', color: '#c5c5c5' },
  license: { glyph: 'shield', color: '#cbcb41' },
  'license.md': { glyph: 'shield', color: '#cbcb41' },
  'license.txt': { glyph: 'shield', color: '#cbcb41' },
  contributing: { glyph: 'megaphone', color: '#c5c5c5' },
  'contributing.md': { glyph: 'megaphone', color: '#c5c5c5' },
  dockerfile: { glyph: 'vm', color: '#519aba' },
  'docker-compose.yml': { glyph: 'vm', color: '#519aba' },
  'docker-compose.yaml': { glyph: 'vm', color: '#519aba' },
  '.gitlab-ci.yml': { glyph: 'beaker', color: '#e8833a' },
  '.travis.yml': { glyph: 'beaker', color: '#c5c5c5' },
  'code_of_conduct.md': { glyph: 'megaphone', color: '#c5c5c5' },
  'code_of_conduct': { glyph: 'megaphone', color: '#c5c5c5' },
  'security.md': { glyph: 'shield', color: '#cbcb41' },
  security: { glyph: 'shield', color: '#cbcb41' },
  'pnpm-lock.yaml': { glyph: 'tag', color: '#cbcb41' },
  'yarn.lock': { glyph: 'tag', color: '#519aba' },
  'npm-shrinkwrap.json': { glyph: 'tag', color: '#cc3e44' },
  makefile: { glyph: 'gear', color: '#858585' },
  'makefile.win': { glyph: 'gear', color: '#858585' },
  caddyfile: { glyph: 'gear', color: '#858585' },
  'deno.json': { glyph: 'symbol-misc', color: '#858585' },
  'deno.jsonc': { glyph: 'symbol-misc', color: '#858585' },
}

const PREFIX_MAP: Array<{ prefix: string; icon: IconDef }> = [
  { prefix: '.eslintrc', icon: { glyph: 'gear', color: '#519aba' } },
  { prefix: '.prettierrc', icon: { glyph: 'gear', color: '#519aba' } },
  { prefix: '.env', icon: { glyph: 'lock', color: '#e6d460' } },
  { prefix: 'readme', icon: { glyph: 'markdown', color: '#519aba' } },
  { prefix: 'changelog', icon: { glyph: 'book', color: '#c5c5c5' } },
  { prefix: 'license', icon: { glyph: 'shield', color: '#cbcb41' } },
]

const DEFAULT_ICON: IconDef = { glyph: 'file', color: '#c5c5c5' }

export interface FileIconResult {
  glyph: string
  color: string
}

export function getFileIcon(fileName: string): FileIconResult {
  const lower = fileName.toLowerCase()
  const exact = NAME_MAP[lower]
  if (exact) return { glyph: exact.glyph, color: exact.color ?? '#c5c5c5' }
  for (const { prefix, icon } of PREFIX_MAP) {
    if (lower.startsWith(prefix)) return { glyph: icon.glyph, color: icon.color ?? '#c5c5c5' }
  }
  const dotIndex = lower.lastIndexOf('.')
  if (dotIndex > 0) {
    const ext = lower.slice(dotIndex)
    const mapped = ICON_MAP[ext]
    if (mapped) return { glyph: mapped.glyph, color: mapped.color ?? '#c5c5c5' }
  }
  return { glyph: DEFAULT_ICON.glyph, color: DEFAULT_ICON.color ?? '#c5c5c5' }
}
